#!/bin/sh

set -e
sourcename="curtin"

Usage() {
   cat <<EOF
Usage: [revno [output.tar.gz]]

  Create a tarball of revno (or tag) in output.tar.gz
  revno defaults to \`bzr revno\`.
  output filename defaults to:
   curtin-X.Y~bzrREVNO.tar.gz
  or, if a tag is given:
   curtin-TAG.tar.gz

  if UNCOMMITTED is set to non '0' in environment
  then uncommitted changes will be kept in the tarball.
EOF
}

TEMP_D=""
fail() { echo "$@" 1>&2; exit 1; }
cleanup() {
   [ -z "$TEMP_D" ] || rm -Rf "$TEMP_D"
}

export_uncommitted=""
if [ "${UNCOMMITTED:-0}" != "0" ]; then
   export_uncommitted="--uncommitted"
fi

[ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }

TEMP_D=$(mktemp -d)
trap cleanup EXIT

case "${1:-HEAD}" in
   tag:*)  version="${1#tag:}";;
   HEAD)   revno="$(bzr revno)"; revargs="-r $revno";;
   [0-9]*) revno="$1"          ; revargs="-r $1";;
esac
output="$2"

if [ -z "$version" ]; then
   bzr cat $revargs debian/changelog.trunk > "$TEMP_D/clog" ||
      fail "failed to extract debian/change.log.trunk at $revargs"

   clogver_o=$(sed -n '1s,.*(\([^)]*\)).*,\1,p' $TEMP_D/clog)
   clogver_upstream=${clogver_o%%-*}
   mmm=${clogver_o%%~*}
   version="$mmm~bzr$revno"
fi

if [ -z "$output" ]; then
   output="$sourcename-$version.tar.gz"
fi

bzr export ${export_uncommitted} \
   --format=tgz --root="$sourcename-${version}" $revargs $output
echo "wrote $output"
