#!/bin/sh

topdir=${CURTIN_VMTEST_TOPDIR:-"${WORKSPACE:-$PWD}/output"}
export CURTIN_VMTEST_KEEP_DATA=${CURTIN_VMTEST_KEEP_DATA:-"always:logs"}
export CURTIN_VMTEST_TOPDIR="$topdir"
export CURTIN_VMTEST_LOG=${CURTIN_VMTEST_LOG:-"$topdir/debug.log"}

fail() { echo "$@" 1>&2; exit 1; }

if [ -d "$topdir" ]; then
    fail "topdir '$topdir' existed."
fi
mkdir -p "$topdir" || fail "failed mkdir $topdir"

if [ $# -eq 0 ]; then
   set -- -vv tests/vmtests/
fi

start_s=$(date +%s)
echo "$(date -R): vmtest start: nosetests3 $*"
nosetests3 "$@"
ret=$?
end_s=$(date +%s)
echo "$(date -R): vmtest end [$ret] in $(($end_s-$start_s))s"
exit $ret

# vi: ts=4 expandtab
