#!/bin/sh
set -e

TEMP_D=""
cleanup() {
    [ -z "$TEMP_D" ] || rm -Rf "${TEMP_D}"
}
trap cleanup EXIT

Usage() {
    cat <<EOF
Usage: ${0##*/} [revision]
    create a tarball of revision (default HEAD)

    options:
      -o | --output FILE   write to file
EOF
}

short_opts="ho:v"
long_opts="help,output:,long,verbose"
getopt_out=$(getopt --name "${0##*/}" \
    --options "${short_opts}" --long "${long_opts}" -- "$@") &&
    eval set -- "${getopt_out}" || { Usage 1>&2; exit 1; }

long_opt=""
while [ $# -ne 0 ]; do
    cur=$1; next=$2
    case "$cur" in
        -o|--output) output=$next; shift;;
           --long) long_opt="--long";;
        --) shift; break;;
    esac
    shift;
done

rev=${1:-HEAD}
version=$(git describe --abbrev=8 "--match=[0-9][0-9]*" ${long_opt} $rev)

archive_base="curtin-$version"
if [ -z "$output" ]; then
    output="$archive_base.tar.gz"
fi

TEMP_D=$(mktemp -d)
tar=${output##*/}
tar="$TEMP_D/${tar%.gz}"
git archive --format=tar --prefix="$archive_base/" "$rev" > "$tar"
gzip -9 -c "$tar" > "$output"
echo "$output"
