#!/bin/bash

PYTHON_VERSION=${PYTHON_VERSION:-3}
pycheck_dirs=( "curtin/" "tests/" )
bin_files=( )
CR="
"


set -f
if [ $# -eq 0 ]; then
   IFS="$CR"
   files=( "${bin_files[@]}" "${pycheck_dirs[@]}" )
   unset IFS
else
   files=( "$@" )
fi

if [ "$PYTHON_VERSION" = "2" ]; then
    pyflakes="pyflakes"
else
    pyflakes="pyflakes3"
fi

cmd=( "$pyflakes" "${files[@]}" )

echo "Running: " "${cmd[@]}" 1>&2
exec "${cmd[@]}"
